### ISSUE TITLE
No target "modal_progress_hud_nsn_plugin"

### ISSUE THREAD

**Issue by MichaelSeibig** [kphanipavan/modal_progress_hud_nsn#10] opened 2023-02-13 16:08 UTC
I have the following message if I launch in Windows in debug mode

Launching lib\main.dart on Windows in debug mode...
main.dart:1
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:modal_progress_hud_nsn_plugin>

  No target "modal_progress_hud_nsn_plugin"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:modal_progress_hud_nsn_plugin>

  No target "modal_progress_hud_nsn_plugin"

CMake Error:

here is flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.8.0-10.0.pre.39, on Microsoft Windows [Versione 10.0.19044.2130], locale it-IT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.75.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

I amusing:  modal_progress_hud_nsn: ^0.3.0

**Comment by kphanipavan** [comment] 2023-02-14 01:57
Duplicate of #6

**Closed as not planned by kphanipavan** 2023-02-14 01:57 UTC
