### ISSUE TITLE
Screen Jump to top on progressIndicator call

### ISSUE THREAD

**Issue by Jimmyjai** [kphanipavan/modal_progress_hud_nsn#2] opened 2022-01-28 06:20 UTC
I was using modal_progress_hud, which doesn't have null safety.
So, I have updated it with modal_progress_hud_nsn.

Issue:
For example, I have a form with 10 textboxes and a submit button. After filling all the textboxes, I must be on the bottom of the screen. 
On submit hit, 
_setState(() {
      _saving = true;
    });_
Which calls the **_progressIndicator_**, and the screen automatically jumps to the top.

But this issue is not there in **modal_progress_hud**.

Please help me out.

**Comment by kphanipavan** [comment] 2022-02-02 01:37
Are you using the [Form](https://api.flutter.dev/flutter/widgets/Form-class.html) class or the [listView](https://api.flutter.dev/flutter/widgets/ListView-class.html) class?

Listview has a passable physics parameter. Try switching between [NeverScrollablePhysics](https://api.flutter.dev/flutter/widgets/NeverScrollableScrollPhysics-class.html) and [AlwaysScrollablePhysics](https://api.flutter.dev/flutter/widgets/AlwaysScrollableScrollPhysics-class.html).

Also try using [modal_progress_hud_alt](https://pub.dev/packages/modal_progress_hud_alt). Its the same as the original package with null safety, with support for more platforms than mine.

Share your results here...

TQ

Edit: Markdown Syntax

**Comment by minhdanh** [comment] 2022-09-25 08:01
I'm having this issue as well with current version

**Comment by kphanipavan** [comment] 2022-09-28 23:48
> Listview has a passable physics parameter. Try switching between [NeverScrollablePhysics](https://api.flutter.dev/flutter/widgets/NeverScrollableScrollPhysics-class.html) and [AlwaysScrollablePhysics](https://api.flutter.dev/flutter/widgets/AlwaysScrollableScrollPhysics-class.html).

Have you tried this fix?

**Comment by minhdanh** [comment] 2022-09-29 00:40
I already tried that but that didn't solve the issue :"(

**Comment by kphanipavan** [comment] 2022-09-29 04:59
Can you post the code snippet here?

I will try to replicate it on my end...

**Comment by minhdanh** [comment] 2023-07-09 03:34
Hi @kphanipavan, I'm still seeing this behavior with the latest version as of now.
I've create a repo to reproduce this. Please see here: https://github.com/minhdanh/test_hud
Basically it's the code from your example with just this addition: https://github.com/minhdanh/test_hud/blob/master/lib/main.dart#L192
After tapping Login button the screen is scrolled to the top of the screen.

**Comment by minhdanh** [comment] 2023-07-09 03:54
Hi @kphanipavan I've created a PR to fix this issue: #12 
Please have a look. Thank you!

**Comment by kphanipavan** [comment] 2023-07-09 04:35
Hi @minhdanh 

Thank you for the contribution, it is working as intended.

Closing this issue for now, open if necessary.

~Pvn

**Closed as completed** 2023-07-09 04:35 UTC
